name: Build Electron App for Windows

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean workspace
        run: |
          if (Test-Path dist) { Remove-Item -Recurse -Force dist }
          if (Test-Path node_modules) { Remove-Item -Recurse -Force node_modules }
          if (Test-Path out) { Remove-Item -Recurse -Force out }
          if (Test-Path .electron-forge) { Remove-Item -Recurse -Force .electron-forge }

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Electron distributables (Forge)
        run: yarn make

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: printer-agent-installer
          path: out/make/**/*.msi